services:
  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      appendonly: yes
      privileged: true
    command: 
      redis-server --port 6379 --requirepass 123456  --appendonly yes
  mysql:
    image: mysql/mysql-server
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    restart: unless-stopped
    # volumes:
    #   - ./seq-data:/data
    environment:
      ACCEPT_EULA: "Y"
  rabbitmq:
    image: rabbitmq:management
    restart: always
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest